---
title: "rethinking-cha4"
author: "ManBuXiaoCun"
date: '2022-05-08'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rethinking)
library(tidyverse)
library(GGally)
library(ggpubr)
theme_set(theme_classic2())
data("Howell1")

```
a glimpse at the Howell1
```{r}
summary(Howell1)
plot(Howell1)
ggpairs(Howell1) # better than plot
```

height-weight gender
```{r}
ggplot(Howell1)+
  geom_point(aes(x = weight, y = height, color = as.factor(male) ))+
  geom_smooth(aes(x = weight, y = height, color = as.factor(male) ), method = 'loess')
```

height modeling
```{r}
curve(dnorm(x, 180, 20), from = 100, to = 260)
```

```{r}
mu <- seq(160,180,by=1)
sigma <- seq(20,40,by=1)

```

```{r}
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
hist(prior_h)

prior_h1 <- rnorm(1e4,sample(x = sample_mu,size=1), sample(x = sample_sigma,size=1))
dens(prior_h1,add = TRUE,col="blue")
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h,add = TRUE,col="red")
z <- rep(NULL, 1e1)
for (i in 1:1e1) {
  z[i] <- rnorm(1,sample(x = sample_mu,size=1), sample(x = sample_sigma,size=1))
  print(sample_mu)
  print(sample_sigma)
}
boxplot(z)
boxplot(prior_h)
```

```{r}
mu1 <- -1:7
sigma1 <- 1:3
pr1 <- rnorm(1e5, mean = mu1, sd = sigma1)
dens(pr1,col="red",add = TRUE, ylim=c(0,1))
```

DAG
```{r}
library(dagitty)
```

```{r}
simpson.simulator <- function(N,s,ce){
	Z1 <- rnorm(N,0,s)
	Z3 <- rnorm(N,0,s) + Z1
	U <- rnorm(N,0,s) + Z1
	Z2 <- rnorm(N,0,s) + Z3 + U
	X <- rnorm(N,0,s) + U
	Y <- rnorm(N,0,s) + ce*X + 10*Z3
	data.frame(Y,X,Z1,Z2,Z3)
}

# 1st parameter: sample size
# 2nd parameter: noise standard deviation
# 3rd parameter: true causal effect
D <- simpson.simulator(1000,0.01,1)



# unadjusted estimate
m <- lm(D[,1:2])
summary(m)
confint(m,'X')
```

```{r}
library(geomtextpath)
library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("ZCOOL XiaoWei", "chinese")
font_add_google("Schoolbell", "bell")

## Automatically use showtext to render text
showtext_auto()


# Set a consistent theme for the plots here
theme_set(theme_minimal() + 
          theme(axis.line = element_line(size = 0.25, colour = "gray75")))

t <- seq(5, -1, length.out = 1000) * pi

spiral <- data.frame(x    = sin(t) * 1:1000, 
                     y    = cos(t) * 1:1000,
                     text = paste("Biology is the best"))

ggplot(spiral, aes(x, y, label = text)) +
  geom_textpath(size = 12, vjust = 2, text_only = TRUE) +
  coord_equal(xlim = c(-1500, 1500), ylim = c(-1500, 1500))+
  labs(x="生物最棒",
       y=NULL)+
  theme_bw()
```

```{r}
library("shinystan")
launch_shinystan_demo()
```

```{r}
y_lim <- 20 # a custom threshold for the horizontal line

ggplot() +
  geom_point(data = mtcars,
             aes(x = hp, y = mpg)) +
  geom_hline(yintercept = y_lim) +
  # Shade area under y_lim
  geom_rect(aes(xmin = 100, xmax = 105, ymin = -Inf, ymax = 30),
            alpha = 1/3,
            fill = "blue") +
  # Shade area above y_lim
  geom_rect(aes(xmin = 100, xmax = 105, ymin = y_lim, ymax = Inf),
            alpha = 1/3,
            fill = "red")+
  geom_rect(aes(xmin = 100, xmax = 105, ymin = 30, ymax = Inf),
            alpha = 1/3,
            fill = "green")+
  annotate("text", x = 110, y = c(15, 25, 32), 
           label = c("text1 china","text2 us","text3 moment"),
           hjust= 0, vjust = -0.5, 
           size = 8)+
  theme_grey()

```
german flag
```{r}
x <- 0:5
y <- 0:5
germanflag <- data.frame(x,y)
ggplot(germanflag) +
  geom_rect(aes(xmin = 0, xmax = 5, ymin = 0, ymax = 1),
            alpha = 1/3,
            fill = "#EEC900")+
  geom_rect(aes(xmin = 0, xmax = 5, ymin = 1, ymax = 2),
            alpha = 1/3,
            fill = "#C1121C")+
  geom_rect(aes(xmin = 0, xmax = 5, ymin = 2, ymax = 3),
            alpha = 1/3,
            fill = "#0A0A0D")+
  annotate("text", x = 0.1, y = c(0, 1, 2), 
           label = c("germanflag"),
           hjust= 0, vjust = -0.5, 
           size = 8)+
  theme_void()
  

```

